### ISSUE TITLE
How to remove buttons and fields? 

### ISSUE THREAD

**Issue by danieramiz** [NearHuscarl/flutter_login#47]
I want to use the plugin but, I don't really need the forgot password or the signup stuff 

I sow the AuthCard class has some methods to build the buttons. Is there a way to remove those? 

Thanks,

**Comment by joaquimorg** [comment]
Yes you can do this :
messages: LoginMessages(
signupButton: '',
forgotPasswordButton: '',
)

**Comment by dhs9004** [comment]
> Yes you can do this :
> messages: LoginMessages(
> signupButton: '',
> forgotPasswordButton: '',
> )

but it still will go to the forgotPasswordButton page

**Comment by evertonAlvaro** [comment]
Hello, you find this in my fork.
hideButtonForgotPassword and hideButtonSignUp Propertys
https://github.com/evertonAlvaro/flutter_login#reference

**Comment by Ramax11** [comment]
@evertonAlvaro How to use your code.. with Flutter login lib..?

**Comment by evertonAlvaro** [comment]
> @evertonAlvaro How to use your code.. with Flutter login lib..?
@Ramax11
```
dependencies:
   flutter_login: 
       git: 
         url: https://github.com/evertonAlvaro/flutter_login.git
         ref: master
```
