### ISSUE TITLE
Can't translate Flushbar titles (Error/Success)

### ISSUE THREAD

**Issue by vptcnt** [NearHuscarl/flutter_login#58]
Hello,

It's not possible to translate the titles of the success & error flushbar toasts.

Could you add the two labels in LoginMessages ?
Thanks

Vincent

**Comment by inoas** [comment]
It is fixed here https://github.com/inoas/flutter_login

You can use it like so in `pubspec.yaml`:
# before

```yaml
  flutter_login: ^1.0.14
```

# after

```yaml
  flutter_login: #^1.0.14
    git:
      url: https://github.com/inoas/flutter_login.git
```
